-- Databse related queries

CREATE DATABASE college;
CREATE DATABASE IF NOT EXISTS college;

DROP DATABASE IF EXISTS company;


USE college;

CREATE TABLE student (
id INT PRIMARY KEY,
name VARCHAR(50),
age INT NOT NULL
);

INSERT INTO student VALUES(1, "TOUQEER", 26);
INSERT INTO student VALUES(3, "ASHRAF", 20);

SELECT * FROM student;

SHOW DATABASE;
